version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: python:3.8
    volumes:
      - '../:/var/www/html'
    container_name: python
    tty: true
    working_dir: '/var/www/html'